services:
  chatlas-bot:
    build: .
    container_name: chatlas-bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - JAVA_OPTS=-Xms256m -Xmx256m
    restart: unless-stopped
